profiles: 
   production: 
      base_url: http://forge.jboss.org/ 
      deploy:
         host: github_pages 
         branch: master
      google_analytics: UA-34467975-1
      metrics_base_url: http://www.redhat.com
